name: Find a PR Comment
description: find a comment to a pull request

inputs:
  token:
    description: "GitHub Token"
    required: true
  pr_number:
    description: "Pull Request number"
    required: true
  author:
    description: "Author of the comment"
    required: false
    default: "Github-Actions[bot]"
  meta_comment:
    description: "Meta comment"
    required: false
    default: "<!-- AUTOMATED PR COMMENT -->"
  find_section:
    description: "Part of the comment looking for"
    required: false
    default: ""
    
runs:
  using: "composite"
  steps:
    - name: Find PR Comment by PR ID
      id: find
      uses: peter-evans/find-comment@v3
      with:
        issue-number: ${{ inputs.pr_number }}
        author: ${{ inputs.author }}
        token: ${{ inputs.token }}
        body-includes: ${{ inputs.meta_comment }}

    - name: Print PR Comment
      shell: bash
      run: |
        echo "${{ steps.find.outputs.body }}"

    - name: Extract Partial Comment
      id: extract
      shell: bash
      run: |
        body=${{ steps.find.outputs.body }}

        if [[ -z "${{ inputs.find_section }}" ]]; then
          result=$body
        else
          result=$(sed -n '/${{ inputs.find_section }}/,/${{ inputs.find_section }}/p' <<< $body)
          result=$(sed '1d;$d' <<< $result)
        fi
        echo "body=$body"
        echo "result=$result"

        echo "result=$result" >> $GITHUB_OUTPUT
outputs:
  comment_id: 
    description: "Comment ID"
    value: ${{ steps.find-comment.outputs.comment_id }}
  result:
    description: "Comment"
    value: ${{ steps.extract.outputs.result }}
  author:
    description: "Author"
    value: ${{ steps.find.outputs.author }}
  created_at:
    description: "Created At"
    value: ${{ steps.find.outputs.comment-created-at }}
  

    