name: Execute Python Script
description: Set up Python environment for running Python scripts and Execute it

inputs:
  python-version:
    description: 'The version of Python to use'
    required: true
    default: '3.8'

  module:
    description: 'The module of the Python file to run'
    required: false
    default: '*'

  debug:
    description: 'Print debug information'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set workspace directory
      shell: bash
      run: |
        if [[ -z "${{ env._PYTHON_WORKSPACE }}" ]]; then
          _PYTHON_WORKSPACE="$GITHUB_WORKSPACE/.python_workspace/scripts"
          echo "_PYTHON_WORKSPACE=$_PYTHON_WORKSPACE" >> $GITHUB_ENV

          echo "_PYTHON_WORKSPACE is set to $_PYTHON_WORKSPACE"
        fi

        echo "_PYTHON_WORKSPACE is already set to $_PYTHON_WORKSPACE"

    # The scripts/${{ inputs.module }} directory is created under $GITHUB_WORKSPACE/.python_workspace
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: xctions/workflows
        ref: main
        path: .python_workspace
        fetch-depth: 0
        sparse-checkout: "scripts/${{ inputs.module }}"
        sparse-checkout-cone-mode: true

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    # If the Python version is not already installed,
    # skip the installation
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # each step in the composite run must be a separate shell
    # so cd doesn't persist between steps
    - name: Install dependencies
      shell: bash
      run: |
        ls -al
        workdir="${{ env._PYTHON_WORKSPACE }}/${{ inputs.module }}"
        cd $workdir
        ls -al
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        echo "workdir=$workdir" >> $GITHUB_OUTPUT

    - name: Execute Python Script
      shell: bash
      run: |
        python "${{ steps.temp.outputs.workdir }}/main.py"