name: Temp Directory
description: Create a temporary directory for storing files

inputs:
  path: 
    description: The path of the file saved to the temporary directory
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check if temporary directory exists
      shell: bash
      run: |
        if [[ -z "${{ env._TEMP_DIR }}" || ! -d "${{ env.$_TEMP_DIR }}" ]]; then
          echo "_TEMP_DIR doesn't exist at $_TEMP_DIR"
          exit 0
        fi
  
    - name: Join the path
      id: join
      shell: bash
      run: |
        if [[ "${{ inputs.path }}" == /* ]]; then
          temp_path="${{ env._TEMP_DIR }}.root${{ inputs.path }}"
          echo "input path starts with /"
        else
          temp_path="${{ env._TEMP_DIR }}${{ inputs.path }}"
          echo "input path doesn't start with /"
        fi
        
        echo ==========================================
        echo "temp_path=$temp_path"
        echo ==========================================

        echo "temp_path=$temp_path" >> $GITHUB_OUTPUT


    - name: Check if file exists
      shell: bash
      run: |
        # -e: file or dir exists
        if [[ ! -e "${{ steps.join.outputs.temp_path }}" ]]; then
          echo "File doesn't exist at ${{ steps.join.outputs.temp_path }}"
          exit 1
        fi

outputs:
  path:
    description: The path to the temporary directory
    value: "${{ steps.join.outputs.temp_path }}"
 
 
