name: Temp Directory
description: Create a temporary directory for storing files

inputs:
  path: 
    description: The path of the file or directory saved to the temporary directory
    required: true
  debug:
    description: 'Print debug information'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Check if temporary directory exists
      shell: bash
      id: exist
      run: |
        if [[ -n "$_TEMP_DIR" && -d "$_TEMP_DIR" ]]; then
          echo "exist=true" >> $GITHUB_OUTPUT
        else
          echo "exist=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Temp Directory If Not Exist
      if: steps.exist.outputs.exist == 'false'
      shell: bash
      run: |
        exist="${{ steps.exist.outputs.exist }}"

        _TEMP_DIR="$GITHUB_WORKSPACE/$(uuidgen)/"
        mkdir -p "$_TEMP_DIR"
        echo "_TEMP_DIR=$_TEMP_DIR" >> $GITHUB_ENV

        echo "Temp directory created at $_TEMP_DIR"
        
    - name: Join the path
      id: join
      shell: bash
      run: |
        # Check if the path starts with /
        if [[ "${{ inputs.path }}" == /* ]]; then
          temp_path="$_TEMP_DIR.root${{ inputs.path }}"
          echo "input path starts with /"
        else
          temp_path="$_TEMP_DIR./${{ inputs.path }}"
          echo "input path doesn't start with /"
        fi
        
        echo "temp_path=$temp_path" >> $GITHUB_OUTPUT

    - name: Copy File to Temp Directory
      shell: bash
      run: |
        cp -R "${{ inputs.path }}" "$_TEMP_DIR"

    - name: Debug Info
      shell: bash
      if: ${{ inputs.debug == 'true' }}
      run: |
        echo ==============================================
        echo "temp_path=${{ steps.join.outputs.temp_path }}"
        ls -l "$_TEMP_DIR"
        echo ==============================================
  
outputs:
  temp_path:
    description: The path to the temporary directory
    value: "${{ steps.join.outputs.temp_path }}"
 
 
